// Generated by gencpp from file project_pkg/Music.msg
// DO NOT EDIT!


#ifndef PROJECT_PKG_MESSAGE_MUSIC_H
#define PROJECT_PKG_MESSAGE_MUSIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <project_pkg/Note.h>

namespace project_pkg
{
template <class ContainerAllocator>
struct Music_
{
  typedef Music_<ContainerAllocator> Type;

  Music_()
    : notes()  {
    }
  Music_(const ContainerAllocator& _alloc)
    : notes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::project_pkg::Note_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::project_pkg::Note_<ContainerAllocator> >::other >  _notes_type;
  _notes_type notes;





  typedef boost::shared_ptr< ::project_pkg::Music_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_pkg::Music_<ContainerAllocator> const> ConstPtr;

}; // struct Music_

typedef ::project_pkg::Music_<std::allocator<void> > Music;

typedef boost::shared_ptr< ::project_pkg::Music > MusicPtr;
typedef boost::shared_ptr< ::project_pkg::Music const> MusicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_pkg::Music_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_pkg::Music_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'project_pkg': ['/home/eecs106a/SheetMusicRecognition/project_ws/src/project_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_pkg::Music_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_pkg::Music_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_pkg::Music_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_pkg::Music_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_pkg::Music_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_pkg::Music_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_pkg::Music_<ContainerAllocator> >
{
  static const char* value()
  {
    return "336014d282bfb921a1299cf4a485af06";
  }

  static const char* value(const ::project_pkg::Music_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x336014d282bfb921ULL;
  static const uint64_t static_value2 = 0xa1299cf4a485af06ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_pkg::Music_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_pkg/Music";
  }

  static const char* value(const ::project_pkg::Music_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_pkg::Music_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_pkg/Note[] notes\n\
\n\
================================================================================\n\
MSG: project_pkg/Note\n\
int32 key\n\
float32 duration\n\
float32 rest_before\n\
";
  }

  static const char* value(const ::project_pkg::Music_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_pkg::Music_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.notes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Music_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_pkg::Music_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_pkg::Music_<ContainerAllocator>& v)
  {
    s << indent << "notes[]" << std::endl;
    for (size_t i = 0; i < v.notes.size(); ++i)
    {
      s << indent << "  notes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::project_pkg::Note_<ContainerAllocator> >::stream(s, indent + "    ", v.notes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_PKG_MESSAGE_MUSIC_H
